environment:
  matrix:
    - nodejs_version: '8'
    - nodejs_version: '10'
    - nodejs_version: '12'

platform:
  - x64

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm i npminstall && node_modules\.bin\npminstall

test_script:
  - node --version
  - npm --version
  - npm run ci

build: off
